### ISSUE TITLE
Myfox APi connection 

### ISSUE THREAD

**Issue by Unformatic** [Minims/MyFox2MQTT#21]
Bonjour,

Je viens de remarquer que myfox2mqtt ne fonctionne plus.
Mes scénarios HA considere que l'alarme n'est jamais mise.
En regardant dans les logs de docker, je vois un problème de token:

`2024-04-29 15:58:53,252 [WARNING] [__main__:63] API is DEAD, restarting
2024-04-29 15:58:53,253 [INFO] [root:38] Init MyFox2Mqtt
2024-04-29 15:58:53,253 [INFO] [myfox.sso:91] Refreshing Token
Exception in thread Thread-65:
Traceback (most recent call last):
  File "/app/myfox/api/__init__.py", line 78, in _request
    return getattr(self.sso._oauth, method)(url, **kwargs)  # pylint: disable=protected-access
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests_oauthlib/oauth2_session.py", line 483, in request
    url, headers, data = self._client.add_token(
  File "/usr/local/lib/python3.8/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 217, in add_token
    raise TokenExpiredError()
oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "main.py", line 21, in myfox_loop
    myfox_api = MyFox2Mqtt(api=api, mqtt_client=mqtt_client, config=config)
  File "/app/myfox_2_mqtt.py", line 60, in __init__
    sites = self.api.get_sites()
  File "/app/myfox/api/__init__.py", line 126, in get_sites
    response = self.get("/v2/client/site/items")
  File "/app/myfox/api/__init__.py", line 93, in get
    return self._request("get", path)
  File "/app/myfox/api/__init__.py", line 80, in _request
    self.sso._oauth.token = self.sso.refresh_tokens()  # pylint: disable=protected-access
  File "/app/myfox/sso/__init__.py", line 92, in refresh_tokens
    token = self._oauth.refresh_token(MYFOX_TOKEN)
  File "/usr/local/lib/python3.8/site-packages/requests_oauthlib/oauth2_session.py", line 452, in refresh_token
    self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/local/lib/python3.8/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 427, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/local/lib/python3.8/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 441, in parse_token_response
    validate_token_parameters(params)
  File "/usr/local/lib/python3.8/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 448, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/usr/local/lib/python3.8/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 400, in raise_from_error
    raise CustomOAuth2Error(error=error, **kwargs)
oauthlib.oauth2.rfc6749.errors.CustomOAuth2Error: (Temporary blacklisted, 10 failed attempts)`

J'ai vérifié sur https://api.myfox.me/dev/apps mon token est bien indiqué comme activé.
Est ce que d'autres personnes ont ce problème?

Merci d'avance

**Comment by Minims** [comment]
Hello, essaye d'effacer le fichier token.conf qui est créé dans le repertoire myFox2mqtt
